### ISSUE TITLE
Using macOS native linker to generate tests causes warnings

### ISSUE THREAD

**Issue by SevenBits** [toddgaunt/libstx#3]
When compiling the test cases on macOS Sierra (10.12.4), I receive many warnings similar to the following:

    CC test/test_stxalloc.c
    ld: warning: option -s is obsolete and being ignored
    warning: no debug symbols in executable (-arch x86_64)
    CC test/test_stxapp.c
    ld: warning: option -s is obsolete and being ignored
    warning: no debug symbols in executable (-arch x86_64)
    CC test/test_stxavail.c
    ld: warning: option -s is obsolete and being ignored
    warning: no debug symbols in executable (-arch x86_64)

Software:

- clang: Apple LLVM version 8.1.0 (clang-802.0.42)
- ld: ld64-278.4; LLVM version 8.1.0, (clang-802.0.42)

**Comment by toddgaunt** [comment]
Ah, ok. I wasn't aware macOS deprecated that option. I'll look into it.

**Comment by toddgaunt** [comment]
Just so you know its just a flag for stripping symbol information from the binary and it's unnecessary so I have simply removed it for now. It should hopefully compile without warnings for you know.
